# Generated by Django 5.1.3 on 2024-11-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryfood', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=320)),
                ('phone', models.CharField(max_length=11)),
            ],
        ),
    ]
