# Generated by Django 5.1.3 on 2024-11-12 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryfood', '0004_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveryfood.profile')),
                ('id_user_addresses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveryfood.address')),
            ],
        ),
    ]
