# Generated by Django 5.1.3 on 2024-11-12 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryfood', '0005_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.SmallIntegerField(default=0)),
                ('id_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveryfood.order')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveryfood.product')),
            ],
        ),
    ]
