# Generated by Django 5.1.3 on 2024-11-22 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryfood', '0007_alter_address_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='id_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='historicaladdress',
            old_name='id_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='historicalorder',
            old_name='id_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='historicalorder',
            old_name='id_user_addresses',
            new_name='user_addresses',
        ),
        migrations.RenameField(
            model_name='historicalordereditem',
            old_name='id_order',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='historicalordereditem',
            old_name='id_product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='historicalproduct',
            old_name='id_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='id_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='id_user_addresses',
            new_name='user_addresses',
        ),
        migrations.RenameField(
            model_name='ordereditem',
            old_name='id_order',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='ordereditem',
            old_name='id_product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='id_category',
            new_name='category',
        ),
    ]
