# Generated by Django 5.1.3 on 2025-01-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryfood', '0008_rename_id_user_address_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='image',
            field=models.TextField(blank=True, max_length=100, verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
