# Generated by Django 5.1.3 on 2024-12-26 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryfood', '0008_rename_id_user_address_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='slug',
            field=models.SlugField(default='default-slug', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='default-slug', null=True, unique=True),
        ),
    ]
