# Generated by Django 5.1.3 on 2024-12-26 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryfood', '0009_historicalproduct_slug_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproduct',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
