# Generated by Django 5.1.3 on 2025-01-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryfood', '0009_historicalproduct_image_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='file',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='product_files/'),
        ),
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
