# Generated by Django 5.1.3 on 2025-01-19 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryfood', '0011_alter_product_options_historicalprofile_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
